<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Institucion;

class InstitucionSeeder extends Seeder
{
    public function run(): void
    {
        $instituciones = [
            ['id' => 1, 'nombre' => 'C.E.R EL TARRA', 'municipio_id' => 1],
            ['id' => 2, 'nombre' => 'CENT EDUC RUR CAMPANARIO', 'municipio_id' => 1],
            ['id' => 3, 'nombre' => 'CENT EDUC RUR LLANO ALTO', 'municipio_id' => 1],
            ['id' => 4, 'nombre' => 'CENTRO EDUCATIVO RURAL BAJO PAVEZ', 'municipio_id' => 1],
            ['id' => 5, 'nombre' => 'CENTRO EDUCATIVO RURAL CASITAS', 'municipio_id' => 1],
            ['id' => 6, 'nombre' => 'CENT EDUC RUR CHAPINERO', 'municipio_id' => 1],
            ['id' => 7, 'nombre' => 'SEDE CASA DE TEJA', 'municipio_id' => 1],
            ['id' => 8, 'nombre' => 'SEDE EL ARADO', 'municipio_id' => 1],
            ['id' => 9, 'nombre' => 'SEDE EL SALADO', 'municipio_id' => 1],
            ['id' => 10, 'nombre' => 'SEDE EL TABACO', 'municipio_id' => 1],
            ['id' => 11, 'nombre' => 'SEDE HIGUERON', 'municipio_id' => 1],
            ['id' => 12, 'nombre' => 'SEDE LA CALERA', 'municipio_id' => 1],
            ['id' => 13, 'nombre' => 'SEDE LA LABRANZA', 'municipio_id' => 1],
            ['id' => 14, 'nombre' => 'SEDE LA LABRANZA SITIO NUEVO', 'municipio_id' => 1],
            ['id' => 15, 'nombre' => 'SEDE LLANO SUAREZ', 'municipio_id' => 1],
            ['id' => 16, 'nombre' => 'SEDE LOMA DE PAJA', 'municipio_id' => 1],
            ['id' => 17, 'nombre' => 'SEDE LOS ASIENTOS', 'municipio_id' => 1],
            ['id' => 18, 'nombre' => 'SEDE LOS CUROS', 'municipio_id' => 1],
            ['id' => 19, 'nombre' => 'SEDE LOS LLANITOS', 'municipio_id' => 1],
            ['id' => 20, 'nombre' => 'SEDE OROPOMA', 'municipio_id' => 1],
            ['id' => 21, 'nombre' => 'SEDE PIÑITOS', 'municipio_id' => 1],
            ['id' => 22, 'nombre' => 'CENTRO EDUCATIVO RURAL LA MARIA', 'municipio_id' => 1],
            ['id' => 23, 'nombre' => 'CENTRO EDUCATIVO RURAL LA SIERRA', 'municipio_id' => 1],
            ['id' => 24, 'nombre' => 'CENTRO EDUCATIVO RURAL PLAYONCITOS', 'municipio_id' => 1],
            ['id' => 25, 'nombre' => 'COL CARLOS JULIO TORRADO PE¿ARANDA', 'municipio_id' => 1],
            ['id' => 26, 'nombre' => 'COL SANTA BARBARA', 'municipio_id' => 1],
            ['id' => 27, 'nombre' => 'INSTITUCION EDUCATIVA RURAL CAPITANLARGO', 'municipio_id' => 1],
            ['id' => 28, 'nombre' => 'INSTITUCION EDUCATIVA RURAL LA VEGA DEL TIGRE', 'municipio_id' => 1],
            ['id' => 29, 'nombre' => 'INSTITUCION EDUCATIVA RURAL SAN JAVIER', 'municipio_id' => 1],
            ['id' => 30, 'nombre' => 'CENTRO EDUCATIVO RURAL SIRAVITA', 'municipio_id' => 2],
            ['id' => 31, 'nombre' => 'INSTITUCIÓN EDUCATIVA ANTONIO JOSE DE SUCRE', 'municipio_id' => 2],
            ['id' => 32, 'nombre' => 'INSTITUCION EDUCATIVA RURAL SAN JOSE DE CASTRO', 'municipio_id' => 2],
            ['id' => 33, 'nombre' => 'INSTITUCIÓN EDUCATIVA SAN JUAN BOSCO', 'municipio_id' => 2],
            ['id' => 34, 'nombre' => 'CENTRO EDUCATIVO RURAL LA COLONIA', 'municipio_id' => 3],
            ['id' => 35, 'nombre' => 'INST EDUCATIVA  MARCOS GARCIA CARRILLO', 'municipio_id' => 3],
            ['id' => 36, 'nombre' => 'INST EDUCATIVA ANDRES BELLO', 'municipio_id' => 3],
            ['id' => 37, 'nombre' => 'CENTRO EDUCATIVO RURAL AGUA BLANCA', 'municipio_id' => 4],
            ['id' => 38, 'nombre' => 'CENTRO EDUCATIVO RURAL LA CURVA', 'municipio_id' => 4],
            ['id' => 39, 'nombre' => 'INSTITUCIÓN EDUCATIVA COLEGIO RAFAEL CELEDON', 'municipio_id' => 4],
            ['id' => 40, 'nombre' => 'INSTITUCIÓN EDUCATIVA LA SANJUANA', 'municipio_id' => 4],
            ['id' => 41, 'nombre' => 'CENTRO EDUCATIVO RURAL LA PRIMAVERA', 'municipio_id' => 5],
            ['id' => 42, 'nombre' => 'COLEGIO INTEGRADO REYES ARAQUE', 'municipio_id' => 5],
            ['id' => 43, 'nombre' => 'INST EDUCATIVA COL NUESTRA SEÑORA DEL ROSARIO', 'municipio_id' => 5],
            ['id' => 44, 'nombre' => 'INSTITUCION EDUCATIVA RURAL LA CARRERA', 'municipio_id' => 5],
            ['id' => 45, 'nombre' => 'INSTITUTO TECNICO AGRICOLA', 'municipio_id' => 5],
            ['id' => 46, 'nombre' => 'CENTRO EDUCATIVO RURAL LA FENICIA', 'municipio_id' => 6],
            ['id' => 47, 'nombre' => 'COLEGIO ORTUN VELASCO', 'municipio_id' => 6],
            ['id' => 48, 'nombre' => 'CENTRO EDUCATIVO RURAL ISCALA SUR', 'municipio_id' => 7],
            ['id' => 49, 'nombre' => 'CENTRO EDUCATIVO RURAL LA VICTORIA', 'municipio_id' => 7],
            ['id' => 50, 'nombre' => 'CENTRO EDUCATIVO RURAL PALO COLORADO', 'municipio_id' => 7],
            ['id' => 51, 'nombre' => 'COLEGIO NACIONAL SAN LUIS GONZAGA', 'municipio_id' => 7],
            ['id' => 52, 'nombre' => 'INSTITUCION EDUCATIVA TECNICA NUESTRA SEÑORA DE LA PRESENTACION', 'municipio_id' => 7],
            ['id' => 53, 'nombre' => 'INSTITUTO TÉCNICO AGROPECUARIO', 'municipio_id' => 7],
            ['id' => 54, 'nombre' => 'CENT EDUC RUR PRESIDENTE', 'municipio_id' => 8],
            ['id' => 55, 'nombre' => 'CENT EDUC RUR TANE', 'municipio_id' => 8],
            ['id' => 56, 'nombre' => 'CENTRO EDUCATIVO RURAL PUENTE REAL', 'municipio_id' => 8],
            ['id' => 57, 'nombre' => 'CENTRO EDUCATIVO RURAL SAN LUIS DE CHUCARIMA', 'municipio_id' => 8],
            ['id' => 58, 'nombre' => 'INST EDUCATIVA ALONSO CARVAJAL PERALTA', 'municipio_id' => 8],
            ['id' => 59, 'nombre' => 'CENTRO EDUCATIVO RURAL LLANO GRANDE', 'municipio_id' => 9],
            ['id' => 60, 'nombre' => 'CENTRO ETNOEDUCATIVO RURAL YERARO MIMAY SASHIYI', 'municipio_id' => 9],
            ['id' => 61, 'nombre' => 'INSTITUCION EDUCATIVA COLEGIO GUILLERMO QUINTERO CALDERON', 'municipio_id' => 9],
            ['id' => 62, 'nombre' => 'INSTITUCIÓN EDUCATIVA NORMAL SUPERIOR', 'municipio_id' => 9],
            ['id' => 63, 'nombre' => 'INSTITUCION EDUCATIVA PEDRO CARREÑO LEMUS', 'municipio_id' => 9],
            ['id' => 64, 'nombre' => 'INSTITUCION EDUCATIVA RURAL EL GUAMAL', 'municipio_id' => 9],
            ['id' => 65, 'nombre' => 'INSTITUCION EDUCATIVA RURAL HONDURAS MOTILONIA', 'municipio_id' => 9],
            ['id' => 66, 'nombre' => 'INSTITUCION EDUCATIVA RURAL LUIS EDUARDO PEREZ', 'municipio_id' => 9],
            ['id' => 67, 'nombre' => 'INSTITUTO TECNICO AGRICOLA', 'municipio_id' => 9],
            ['id' => 68, 'nombre' => 'CENT EDUC RUR AGUADAS BAJO', 'municipio_id' => 10],
            ['id' => 69, 'nombre' => 'CENTRO EDUCATIVO RURAL CUCUTILLITA', 'municipio_id' => 10],
            ['id' => 70, 'nombre' => 'CENTRO EDUCATIVO RURAL MARIA AUXILIADORA', 'municipio_id' => 10],
            ['id' => 71, 'nombre' => 'CENTRO EDUCATIVO RURAL ROMAN', 'municipio_id' => 10],
            ['id' => 72, 'nombre' => 'COL MONSEÑOR RICARDO TRUJILLO', 'municipio_id' => 10],
            ['id' => 73, 'nombre' => 'CENTRO EDUCATIVO RURAL JUANA BERBESI', 'municipio_id' => 11],
            ['id' => 74, 'nombre' => 'INSTITUCIÓN EDUCATIVA COLEGIO JOSE MARIA CORDOBA', 'municipio_id' => 11],
            ['id' => 75, 'nombre' => 'CENTRO EDUCATIVA RURAL PLAYAS LINDAS', 'municipio_id' => 12],
            ['id' => 76, 'nombre' => 'CENTRO EDUCATIVO RURAL EL CHAMIZON', 'municipio_id' => 12],
            ['id' => 77, 'nombre' => 'CENTRO EDUCATIVO RURAL EL SUL', 'municipio_id' => 12],
            ['id' => 78, 'nombre' => 'CENTRO EDUCATIVO RURAL LA BOGOTANA', 'municipio_id' => 12],
            ['id' => 79, 'nombre' => 'COL ENRIQUE PARDO FARELO', 'municipio_id' => 12],
            ['id' => 80, 'nombre' => 'INST EDUCATIVA COLEGIO SANTO ANGEL', 'municipio_id' => 12],
            ['id' => 81, 'nombre' => 'INSTITUCION EDUCATIVA RURAL SANTA INÉS', 'municipio_id' => 12],
            ['id' => 82, 'nombre' => 'INSTITUCION ETNOEDUCATIVA RURAL IKI BOGYIRA MIMAY.', 'municipio_id' => 12],
            ['id' => 83, 'nombre' => 'INSTITUCIÓN EDUCATIVA COLEGIO MONSEÑOR DIAZ PLATA', 'municipio_id' => 13],
            ['id' => 84, 'nombre' => 'INSTITUCION EDUCATIVA FILO EL GRINGO', 'municipio_id' => 13],
            ['id' => 85, 'nombre' => 'INSTITUCION EDUCATIVA ORU BAJO', 'municipio_id' => 13],
            ['id' => 86, 'nombre' => 'INSTITUCION EDUCATIVA RURAL BELLAVISTA', 'municipio_id' => 13],
            ['id' => 87, 'nombre' => 'INSTITUCION EDUCATIVA RURAL BRACITOS', 'municipio_id' => 13],
            ['id' => 88, 'nombre' => 'INSTITUCION EDUCATIVA RURAL DOMINGO SAVIO', 'municipio_id' => 13],
            ['id' => 89, 'nombre' => 'C.E.R. LA ANGELITA', 'municipio_id' => 14],
            ['id' => 90, 'nombre' => 'CENT EDUC RUR FLORENTINO BLANCO', 'municipio_id' => 14],
            ['id' => 91, 'nombre' => 'INST AGRICOLA RISARALDA', 'municipio_id' => 14],
            ['id' => 92, 'nombre' => 'INST EDUCATIVA  FRANCISCO DE PAULA SANTANDER', 'municipio_id' => 14],
            ['id' => 93, 'nombre' => 'INSTITUCIÓN EDUCATIVA COLEGIO INTEGRADO MARCO FIDEL SUAREZ', 'municipio_id' => 14],
            ['id' => 94, 'nombre' => 'INSTITUCION EDUCATIVA RURAL SAN JOSE DE CALASANZ', 'municipio_id' => 14],
            ['id' => 95, 'nombre' => 'CENTRO EDUCATIVO RURAL SAN ISIDRO', 'municipio_id' => 15],
            ['id' => 96, 'nombre' => 'INSTITUCIÓN EDUCATIVA COLEGIO SAGRADO CORAZON DE JESUS', 'municipio_id' => 15],
            ['id' => 97, 'nombre' => 'INSTITUTO TECNICO AGRICOLA', 'municipio_id' => 15],
            ['id' => 98, 'nombre' => 'INSTITUCION EDUCATIVA COLEGIO SAN MIGUEL', 'municipio_id' => 16],
            ['id' => 99, 'nombre' => 'INSTITUCION EDUCATIVA RURAL EL TARRA', 'municipio_id' => 16],
            ['id' => 100, 'nombre' => 'INSTITUCION EDUCATIVA RURAL MESITAS', 'municipio_id' => 16],
            ['id' => 101, 'nombre' => 'INSTITUCION EDUCATIVA RURAL SAN SEBASTIAN', 'municipio_id' => 16],
            ['id' => 102, 'nombre' => 'INSTITUCION EDUCATIVA COLEGIO PERPETUO SOCORRO', 'municipio_id' => 17],
            ['id' => 103, 'nombre' => 'CENTRO EDUCATIVO RURAL CRISTO REY', 'municipio_id' => 18],
            ['id' => 104, 'nombre' => 'CENTRO EDUCATIVO RURAL EL TROPEZON', 'municipio_id' => 18],
            ['id' => 105, 'nombre' => 'CENTRO EDUCATIVO RURAL LOS CEDROS', 'municipio_id' => 18],
            ['id' => 106, 'nombre' => 'CENTRO EDUCATIVO RURAL VIJAGUAL', 'municipio_id' => 18],
            ['id' => 107, 'nombre' => 'COL EDUARDO COTE LAMUS', 'municipio_id' => 18],
            ['id' => 108, 'nombre' => 'INST EDUCATIVA COL CONDE SAN GERMAN', 'municipio_id' => 18],
            ['id' => 109, 'nombre' => 'INST EDUCATIVA JESUS ANTONIO RAMIREZ', 'municipio_id' => 18],
            ['id' => 110, 'nombre' => 'INSTITUCION EDUCATIVA RURAL LEON XIII', 'municipio_id' => 18],
            ['id' => 111, 'nombre' => 'CENTRO EDUCATIVO RURAL CERRO VIEJO', 'municipio_id' => 19],
            ['id' => 112, 'nombre' => 'CENTRO EDUCATIVO RURAL MESA RICA', 'municipio_id' => 19],
            ['id' => 113, 'nombre' => 'CENTRO EDUCATIVO RURAL SAN PEDRO', 'municipio_id' => 19],
            ['id' => 114, 'nombre' => 'INST EDUCATIVA COL FRAY JOSE MARIA AREVALO', 'municipio_id' => 19],
            ['id' => 115, 'nombre' => 'INST EDUCATIVA COL INTEGRADO GILBERTO CLARO LOZANO', 'municipio_id' => 19],
            ['id' => 116, 'nombre' => 'INSTITUCION EDUCATIVA RURAL BENJAMIN QUINTERO ALVAREZ', 'municipio_id' => 19],
            ['id' => 117, 'nombre' => 'CENTRO EDUCATIVO RURAL CHONA', 'municipio_id' => 20],
            ['id' => 118, 'nombre' => 'COL INTEGRADO NUESTRA SE¿ORA DE LAS ANGUSTIAS', 'municipio_id' => 20],
            ['id' => 119, 'nombre' => 'INSTITUCION EDUCATIVA RURAL SAN BERNARDO DE BALSA', 'municipio_id' => 20],
            ['id' => 120, 'nombre' => 'I.E. ANNA VITIELLO  HOGAR SANTA ROSA DE LIMA', 'municipio_id' => 21],
            ['id' => 121, 'nombre' => 'INST EDUCATIVA COLEGIO ONCE DE NOVIEMBRE', 'municipio_id' => 21],
            ['id' => 122, 'nombre' => 'INST EDUCATIVA INTEGRADO FE Y ALEGRIA', 'municipio_id' => 21],
            ['id' => 123, 'nombre' => 'INST EDUCATIVA LA GARITA', 'municipio_id' => 21],
            ['id' => 124, 'nombre' => 'INST TECNICO MARIO PEZZOTTI LEMUS', 'municipio_id' => 21],
            ['id' => 125, 'nombre' => 'INSTITUTO TECNICO PATIOS CENTRO 2', 'municipio_id' => 21],
            ['id' => 126, 'nombre' => 'CENTRO EDUCATIVO RURAL LA PRIMAVERA', 'municipio_id' => 22],
            ['id' => 127, 'nombre' => 'COL RAIMUNDO ORDO¿EZ YA¿EZ', 'municipio_id' => 22],
            ['id' => 128, 'nombre' => 'CENT EDUC RUR LA SAGRADA FAMILIA', 'municipio_id' => 23],
            ['id' => 129, 'nombre' => 'CENT EDUC RUR SUCRE', 'municipio_id' => 23],
            ['id' => 130, 'nombre' => 'COL NUESTRA SEÑORA DE LA MERCED', 'municipio_id' => 23],
            ['id' => 131, 'nombre' => 'CENT EDUC RUR BUENAVISTA', 'municipio_id' => 24],
            ['id' => 132, 'nombre' => 'CENTRO EDUCATIVO RURAL LLANO DE LOS ALCALDES', 'municipio_id' => 24],
            ['id' => 133, 'nombre' => 'CENTRO EDUCATIVO RURAL PUEBLO NUEVO', 'municipio_id' => 24],
            ['id' => 134, 'nombre' => 'COL AGUSTINA FERRO', 'municipio_id' => 24],
            ['id' => 135, 'nombre' => 'COL EDMUNDO VELASQUEZ', 'municipio_id' => 24],
            ['id' => 136, 'nombre' => 'COL FRANCISCO FERNANDEZ DE CONTRERAS', 'municipio_id' => 24],
            ['id' => 137, 'nombre' => 'COL JOSE EUSEBIO CARO', 'municipio_id' => 24],
            ['id' => 138, 'nombre' => 'COL LA SALLE', 'municipio_id' => 24],
            ['id' => 139, 'nombre' => 'COL RAFAEL CONTRERAS NAVARRO', 'municipio_id' => 24],
            ['id' => 140, 'nombre' => 'I.E. AGUAS CLARAS', 'municipio_id' => 24],
            ['id' => 141, 'nombre' => 'INST TECNICO ALFONSO LOPEZ', 'municipio_id' => 24],
            ['id' => 142, 'nombre' => 'INST TECNICO CARLOS HERNANDEZ YARURO', 'municipio_id' => 24],
            ['id' => 143, 'nombre' => 'INST TECNICO INDUSTRIAL LUCIO PABON NUÑEZ', 'municipio_id' => 24],
            ['id' => 144, 'nombre' => 'INSTITUCION EDUCATIVA LA PRESENTACION', 'municipio_id' => 24],
            ['id' => 145, 'nombre' => 'NORMAL SUPERIOR', 'municipio_id' => 24],
            ['id' => 146, 'nombre' => 'CENTRO EDUCATIVO RURAL CHICHIRA', 'municipio_id' => 25],
            ['id' => 147, 'nombre' => 'COL AGUEDA GALLARDO DE VILLAMIZAR', 'municipio_id' => 25],
            ['id' => 148, 'nombre' => 'COL LA PRESENTACION', 'municipio_id' => 25],
            ['id' => 149, 'nombre' => 'COL PROVINCIAL SAN JOSE', 'municipio_id' => 25],
            ['id' => 150, 'nombre' => 'INST ARQUIDIOCESANO SAN FRANCISCO DE ASIS', 'municipio_id' => 25],
            ['id' => 151, 'nombre' => 'INST EDUCATIVA BETHLEMITAS BRIGHTON', 'municipio_id' => 25],
            ['id' => 152, 'nombre' => 'INSTITUCION EDUCATIVA RURAL SAN MIGUEL', 'municipio_id' => 25],
            ['id' => 153, 'nombre' => 'NORMAL SUPERIOR', 'municipio_id' => 25],
            ['id' => 154, 'nombre' => 'COL NUESTRA SEÑORA DEL PILAR', 'municipio_id' => 26],
            ['id' => 155, 'nombre' => 'INSTITUCIÓN EDUCATIVA EL DIAMANTE', 'municipio_id' => 26],
            ['id' => 156, 'nombre' => 'INSTITUCION EDUCATIVA RURAL GUAYABALES', 'municipio_id' => 26],
            ['id' => 157, 'nombre' => 'COL PUERTO SANTANDER', 'municipio_id' => 27],
            ['id' => 158, 'nombre' => 'CENT EDUC RUR BUENOS AIRES', 'municipio_id' => 28],
            ['id' => 159, 'nombre' => 'CENTRO EDUCATIVO RURAL LA UNION', 'municipio_id' => 28],
            ['id' => 160, 'nombre' => 'COL NUESTRA SE¿ORA DE LA MERCED', 'municipio_id' => 28],
            ['id' => 161, 'nombre' => 'CENTRO EDUCATIVO RURAL FILO REAL', 'municipio_id' => 29],
            ['id' => 162, 'nombre' => 'CENTRO EDUCATIVO RURAL MONTECRISTO', 'municipio_id' => 29],
            ['id' => 163, 'nombre' => 'COL INTEGRADO NUESTRA SE¿ORA DEL CARMEN', 'municipio_id' => 29],
            ['id' => 164, 'nombre' => 'INST TECNICO NUESTRA SEÑORA DE BELEN', 'municipio_id' => 29],
            ['id' => 165, 'nombre' => 'INSTITUTO TECNICO AGRICOLA', 'municipio_id' => 29],
            ['id' => 166, 'nombre' => 'COL CAYETANO FRANCO PINZON', 'municipio_id' => 30],
            ['id' => 167, 'nombre' => 'INSTITUCION EDUCATIVA RURAL BALSAMINA', 'municipio_id' => 30],
            ['id' => 168, 'nombre' => 'INSTITUCION EDUCATIVA RURAL LA FORTUNA', 'municipio_id' => 30],
            ['id' => 169, 'nombre' => 'INSTITUCION EDUCATIVA RURAL LA QUINA', 'municipio_id' => 30],
            ['id' => 170, 'nombre' => 'INSTITUCION EDUCATIVA RURAL SAN JUAN', 'municipio_id' => 30],
            ['id' => 171, 'nombre' => 'INSTITUCION EDUCATIVA RURAL SANTA CATALINA', 'municipio_id' => 30],
            ['id' => 172, 'nombre' => 'COL TEODORO GUTIERREZ CALDERON', 'municipio_id' => 31],
            ['id' => 173, 'nombre' => 'INSTITUCIÓN EDUCATIVA CORNEJO', 'municipio_id' => 31],
            ['id' => 174, 'nombre' => 'CENTRO EDUCATIVO RURAL EL PARAMO', 'municipio_id' => 32],
            ['id' => 175, 'nombre' => 'SANTIAGO APOSTOL', 'municipio_id' => 32],
            ['id' => 176, 'nombre' => 'CENTRO EDUCATIVO RURAL EL RECREO', 'municipio_id' => 33],
            ['id' => 177, 'nombre' => 'CENTRO EDUCATIVO RURAL LAS MESAS', 'municipio_id' => 33],
            ['id' => 178, 'nombre' => 'CENTRO EDUCATIVO RURAL SAN GIL', 'municipio_id' => 33],
            ['id' => 179, 'nombre' => 'COL ALIRIO VERGEL PACHECO', 'municipio_id' => 33],
            ['id' => 180, 'nombre' => 'COL NTRA SRA DE LAS MERCEDES', 'municipio_id' => 33],
            ['id' => 181, 'nombre' => 'INST. EDUCATIVA ARGELINO DURAN QUINTERO', 'municipio_id' => 33],
            ['id' => 182, 'nombre' => 'INST. EDUCATIVA MONSE¿OR SARMIENTO PERALTA', 'municipio_id' => 33],
            ['id' => 183, 'nombre' => 'INSTITUCION EDUCATIVA RURAL LA DIVINA ESPERANZA', 'municipio_id' => 33],
            ['id' => 184, 'nombre' => 'INSTITUCION EDUCATIVA RURAL NUESTRA SEÑORA DEL CARMEN', 'municipio_id' => 33],
            ['id' => 185, 'nombre' => 'INSTITUCION EDUCATIVA RURAL SAN ROQUE', 'municipio_id' => 33],
            ['id' => 186, 'nombre' => 'INSTITUCION EDUCATIVA SAN LUIS BELTRAN', 'municipio_id' => 33],
            ['id' => 187, 'nombre' => 'CENT EDUC RUR LA LAGUNA', 'municipio_id' => 34],
            ['id' => 188, 'nombre' => 'INSTITUCION EDUCATIVA LUIS ERNESTO PUYANA', 'municipio_id' => 34],
            ['id' => 189, 'nombre' => 'INSTITUCION EDUCATIVA RURAL BABEGA', 'municipio_id' => 34],
            ['id' => 190, 'nombre' => 'CENTRO EDUCATIVO RURAL EL FARACHE', 'municipio_id' => 35],
            ['id' => 191, 'nombre' => 'CENTRO ETNOEDUCATIVO RURAL CAMARIGCAYNA BARI', 'municipio_id' => 35],
            ['id' => 192, 'nombre' => 'COL EMILIANO SANTIAGO QUINTERO', 'municipio_id' => 35],
            ['id' => 193, 'nombre' => 'INSTITUCION EDUCATIVA EL ASERRIO', 'municipio_id' => 35],
            ['id' => 194, 'nombre' => 'INSTITUCION EDUCATIVA INSTITUTO AGRICOLA REGION DEL CATATUMBO', 'municipio_id' => 35],
            ['id' => 195, 'nombre' => 'INSTITUCION EDUCATIVA RURAL LA CECILIA', 'municipio_id' => 35],
            ['id' => 196, 'nombre' => 'INSTITUCION EDUCATIVA RURAL LOS MESONES', 'municipio_id' => 35],
            ['id' => 197, 'nombre' => 'INSTITUCION EDUCATIVA SAN JUANCITO', 'municipio_id' => 35],
            ['id' => 198, 'nombre' => 'CENTRO EDUCATIVO RURAL LA LIBERTAD', 'municipio_id' => 36],
            ['id' => 199, 'nombre' => 'I.E. COL INTEG FRANCISCO JOSE DE CALDAS', 'municipio_id' => 36],
            ['id' => 200, 'nombre' => 'INST EDUCATIVA CONCENTRACION DE DESARROLLO RUR LA GABARRA', 'municipio_id' => 36],
            ['id' => 201, 'nombre' => 'INST EDUCATIVA INTEGRADO CAMPO DOS', 'municipio_id' => 36],
            ['id' => 202, 'nombre' => 'INST EDUCATIVA INTEGRADO LA LLANA', 'municipio_id' => 36],
            ['id' => 203, 'nombre' => 'INST EDUCATIVA INTEGRADO PETROLEA', 'municipio_id' => 36],
            ['id' => 204, 'nombre' => 'INSTITUCION EDUCATIVA HORACIO OLAVE', 'municipio_id' => 36],
            ['id' => 205, 'nombre' => 'INSTITUCION EDUCATIVA RURAL BERTRANIA', 'municipio_id' => 36],
            ['id' => 206, 'nombre' => 'INSTITUCION EDUCATIVA RURAL KILOMETRO 15', 'municipio_id' => 36],
            ['id' => 207, 'nombre' => 'INSTITUCION EDUCATIVA RURAL LA ANGALIA', 'municipio_id' => 36],
            ['id' => 208, 'nombre' => 'INSTITUCION EDUCATIVA RURAL LA SERPENTINA', 'municipio_id' => 36],
            ['id' => 209, 'nombre' => 'INSTITUCION EDUCATIVA RURAL PUERTO BARCO', 'municipio_id' => 36],
            ['id' => 210, 'nombre' => 'INSTITUCION EDUCATIVA RURAL TRES BOCAS', 'municipio_id' => 36],
            ['id' => 211, 'nombre' => 'INTITUCIÓN ETNOEDUCATIVA BARI', 'municipio_id' => 36],
            ['id' => 212, 'nombre' => 'CENTRO EDUCATIVO RURAL LA MESA', 'municipio_id' => 37],
            ['id' => 213, 'nombre' => 'CENTRO EDUCATIVO RURAL LA UNION', 'municipio_id' => 37],
            ['id' => 214, 'nombre' => 'CENTRO EDUCATIVO RURAL PADRE LUIS ANTONIO ROJAS', 'municipio_id' => 37],
            ['id' => 215, 'nombre' => 'CENTRO EDUCATIVO RURAL SANTA BARBARA', 'municipio_id' => 37],
            ['id' => 216, 'nombre' => 'COL GUILLERMO COTE BAUTISTA', 'municipio_id' => 37],
            ['id' => 217, 'nombre' => 'COL SAN BERNARDO', 'municipio_id' => 37],
            ['id' => 218, 'nombre' => 'I.E. INSTITUCIÓN ETNOEDUCATIVA U WA IZQUETA (SEGOVIA)', 'municipio_id' => 37],
            ['id' => 219, 'nombre' => 'I.E. SAMORE', 'municipio_id' => 37],
            ['id' => 220, 'nombre' => 'INSTITUCION EDUCATIVA COLEGIO GIBRALTAR', 'municipio_id' => 37],
            ['id' => 221, 'nombre' => 'INSTITUCION EDUCATIVA RURAL LA CAPILLA', 'municipio_id' => 37],
            ['id' => 222, 'nombre' => 'COL NUESTRA SE¿ORA DEL ROSARIO', 'municipio_id' => 38],
            ['id' => 223, 'nombre' => 'INSTITUCION EDUCATIVA SAN PEDRO APOSTOL', 'municipio_id' => 38],
            ['id' => 224, 'nombre' => 'COL LUIS GABRIEL CASTRO', 'municipio_id' => 39],
            ['id' => 225, 'nombre' => 'COL PRESBITERO ALVARO SUAREZ', 'municipio_id' => 39],
            ['id' => 226, 'nombre' => 'COL SAN ANTONIO', 'municipio_id' => 39],
            ['id' => 227, 'nombre' => 'INST EDUCATIVA LA FRONTERA', 'municipio_id' => 39],
            ['id' => 228, 'nombre' => 'INST TECNICO AGROP JUAN FRIO', 'municipio_id' => 39],
            ['id' => 229, 'nombre' => 'INST TECNICO MARIA INMACULADA', 'municipio_id' => 39],
            ['id' => 230, 'nombre' => 'INST. EDUCATIVA MANUEL ANTONIO RUEDA JARA', 'municipio_id' => 39],
            ['id' => 231, 'nombre' => 'INSTITUCIÓN EDUCATIVA COLEGIO GENERAL SANTANDER', 'municipio_id' => 39],
        ];

        foreach ($instituciones as $institucion) {
            Institucion::updateOrCreate(
                ['id' => $institucion['id']], // Condición de búsqueda
                ['nombre' => $institucion['nombre'], 'municipio_id' => $institucion['municipio_id']] // Datos a actualizar o insertar
            );
        }
    }
}
