<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\CtVerificacionCct;
use Illuminate\Http\Request;
use App\Models\Attachment;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

class CtVerificacionCctController extends Controller
{
    public function index()
    {
        return response()->json(CtVerificacionCct::all());
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'etc' => 'string|nullable',
            'fecha_visita' => 'date|nullable',
            'municipio' => 'string|nullable',
            'institucion' => 'string|nullable',
            'sede' => 'string|nullable',
            'hora_inicial' => 'string|nullable',
            'hora_final' => 'string|nullable',
            'tipo_visita' => 'string|nullable',
            'numero_visita' => 'string|nullable',
            'operador' => 'string|nullable',
            'contrato' => 'string|nullable',
            'num_beneficiarios' => 'integer|nullable',
            'cdp' => 'string|nullable',
            'placa_vehiculo' => 'string|nullable',
            'numero_sedes' => 'integer|nullable',
            'observaciones_recibe' => 'string|nullable',
            'fecha_fumigacion' => 'date|nullable',
            'fecha_limpieza_tanque' => 'date|nullable',
            'fecha_ultima_visita' => 'date|nullable',
            'concepto_emitido' => 'string|nullable',
            'firma1' => 'string|nullable',
            'firma2' => 'string|nullable',
            'pre_1' => 'string|nullable',
            'pre_1_obs' => 'string|nullable',
            'pre_2' => 'string|nullable',
            'pre_2_obs' => 'string|nullable',
            'pre_3' => 'string|nullable',
            'pre_3_obs' => 'string|nullable',
            'pre_4' => 'string|nullable',
            'pre_4_obs' => 'string|nullable',
            'pre_5' => 'string|nullable',
            'pre_5_obs' => 'string|nullable',
            'pre_6' => 'string|nullable',
            'pre_6_obs' => 'string|nullable',
            'pre_7' => 'string|nullable',
            'pre_7_obs' => 'string|nullable',
            'pre_8' => 'string|nullable',
            'pre_8_obs' => 'string|nullable',
            'pre_9' => 'string|nullable',
            'pre_9_obs' => 'string|nullable',
            'pre_10' => 'string|nullable',
            'pre_10_obs' => 'string|nullable',
            'pre_11' => 'string|nullable',
            'pre_11_obs' => 'string|nullable',
            'pre_12' => 'string|nullable',
            'pre_12_obs' => 'string|nullable',
            'pre_13' => 'string|nullable',
            'pre_13_obs' => 'string|nullable',
            'pre_14' => 'string|nullable',
            'pre_14_obs' => 'string|nullable',
            'pre_15' => 'string|nullable',
            'pre_15_obs' => 'string|nullable',
            'pre_16' => 'string|nullable',
            'pre_16_obs' => 'string|nullable',
            'pre_17' => 'string|nullable',
            'pre_17_obs' => 'string|nullable',
            'pre_18' => 'string|nullable',
            'pre_18_obs' => 'string|nullable',
            'pre_19' => 'string|nullable',
            'pre_19_obs' => 'string|nullable',
            'pre_20' => 'string|nullable',
            'pre_20_obs' => 'string|nullable',
            'pre_21' => 'string|nullable',
            'pre_21_obs' => 'string|nullable',
            'pre_22' => 'string|nullable',
            'pre_22_obs' => 'string|nullable',
            'pre_23' => 'string|nullable',
            'pre_23_obs' => 'string|nullable',
            'pre_24' => 'string|nullable',
            'pre_24_obs' => 'string|nullable',
            'pre_25' => 'string|nullable',
            'pre_25_obs' => 'string|nullable',
            'pre_26' => 'string|nullable',
            'pre_26_obs' => 'string|nullable',
            'pre_27' => 'string|nullable',
            'pre_27_obs' => 'string|nullable',
            'pre_28' => 'string|nullable',
            'pre_28_obs' => 'string|nullable',
            'pre_29' => 'string|nullable',
            'pre_29_obs' => 'string|nullable',
            'pre_30' => 'string|nullable',
            'pre_30_obs' => 'string|nullable',
            'pre_31' => 'string|nullable',
            'pre_31_obs' => 'string|nullable',
            'pre_32' => 'string|nullable',
            'pre_32_obs' => 'string|nullable',
            'pre_33' => 'string|nullable',
            'pre_33_obs' => 'string|nullable',
            'pre_34' => 'string|nullable',
            'pre_34_obs' => 'string|nullable',
            'pre_35' => 'string|nullable',
            'pre_35_obs' => 'string|nullable',
            'pre_36' => 'string|nullable',
            'pre_36_obs' => 'string|nullable',
            'pre_37' => 'string|nullable',
            'pre_37_obs' => 'string|nullable',
            'pre_38' => 'string|nullable',
            'pre_38_obs' => 'string|nullable',
            'pre_39' => 'string|nullable',
            'pre_39_obs' => 'string|nullable',
            'pre_40' => 'string|nullable',
            'pre_40_obs' => 'string|nullable',
            'pre_41' => 'string|nullable',
            'pre_41_obs' => 'string|nullable',
            'pre_42' => 'string|nullable',
            'pre_42_obs' => 'string|nullable',
            'pre_43' => 'string|nullable',
            'pre_43_obs' => 'string|nullable',
            'pre_44' => 'string|nullable',
            'pre_44_obs' => 'string|nullable',
            'pre_45' => 'string|nullable',
            'pre_45_obs' => 'string|nullable',
            'pre_46' => 'string|nullable',
            'pre_46_obs' => 'string|nullable',
            'pre_47' => 'string|nullable',
            'pre_47_obs' => 'string|nullable',
            'pre_48' => 'string|nullable',
            'pre_48_obs' => 'string|nullable',
            'pre_49' => 'string|nullable',
            'pre_49_obs' => 'string|nullable',
            'pre_50' => 'string|nullable',
            'pre_50_obs' => 'string|nullable',
            'pre_51' => 'string|nullable',
            'pre_51_obs' => 'string|nullable',
            'pre_52' => 'string|nullable',
            'pre_52_obs' => 'string|nullable',
            'pre_53' => 'string|nullable',
            'pre_53_obs' => 'string|nullable',
            'pre_54' => 'string|nullable',
            'pre_54_obs' => 'string|nullable',
            'pre_55' => 'string|nullable',
            'pre_55_obs' => 'string|nullable',
            'pre_56' => 'string|nullable',
            'pre_56_obs' => 'string|nullable',
            'pre_57' => 'string|nullable',
            'pre_57_obs' => 'string|nullable',
            'pre_58' => 'string|nullable',
            'pre_58_obs' => 'string|nullable',
            'pre_59' => 'string|nullable',
            'pre_59_obs' => 'string|nullable',
            'pre_60' => 'string|nullable',
            'pre_60_obs' => 'string|nullable',
            'pre_61' => 'string|nullable',
            'pre_61_obs' => 'string|nullable',
            'pre_62' => 'string|nullable',
            'pre_62_obs' => 'string|nullable',
            'pre_63' => 'string|nullable',
            'pre_63_obs' => 'string|nullable',
            'pre_64' => 'string|nullable',
            'pre_64_obs' => 'string|nullable',
            'pre_65' => 'string|nullable',
            'pre_65_obs' => 'string|nullable',
            'pre_66' => 'string|nullable',
            'pre_66_obs' => 'string|nullable',
            'pre_67' => 'string|nullable',
            'pre_67_obs' => 'string|nullable',
            'pre_68' => 'string|nullable',
            'pre_68_obs' => 'string|nullable',
            'pre_69' => 'string|nullable',
            'pre_69_obs' => 'string|nullable',
            'pre_70' => 'string|nullable',
            'pre_70_obs' => 'string|nullable',
            'pre_71' => 'string|nullable',
            'pre_71_obs' => 'string|nullable',
            'pre_72' => 'string|nullable',
            'pre_72_obs' => 'string|nullable',
            'pre_73' => 'string|nullable',
            'pre_73_obs' => 'string|nullable',
            'tb_verificacion1_1' => 'string|nullable',
            'tb_verificacion1_2' => 'string|nullable',
            'tb_verificacion1_3' => 'string|nullable',
            'tb_verificacion1_4' => 'string|nullable',
            'tb_verificacion1_5' => 'string|nullable',
            'tb_verificacion1_6' => 'string|nullable',
            'tb_verificacion1_7' => 'string|nullable',
            'tb_verificacion1_8' => 'string|nullable',
            'tb_verificacion1_9' => 'string|nullable',
            'tb_verificacion2_1' => 'string|nullable',
            'tb_verificacion2_2' => 'string|nullable',
            'tb_verificacion2_3' => 'string|nullable',
            'tb_verificacion2_4' => 'string|nullable',
            'tb_verificacion2_5' => 'string|nullable',
            'tb_verificacion2_6' => 'string|nullable',
            'tb_verificacion2_7' => 'string|nullable',
            'tb_verificacion2_8' => 'string|nullable',
            'tb_verificacion2_9' => 'string|nullable',
            'tb_verificacion3_1' => 'string|nullable',
            'tb_verificacion3_2' => 'string|nullable',
            'tb_verificacion3_3' => 'string|nullable',
            'tb_verificacion3_4' => 'string|nullable',
            'tb_verificacion3_5' => 'string|nullable',
            'tb_verificacion3_6' => 'string|nullable',
            'tb_verificacion3_7' => 'string|nullable',
            'tb_verificacion3_8' => 'string|nullable',
            'tb_verificacion3_9' => 'string|nullable',
            'tb_verificacion4_1' => 'string|nullable',
            'tb_verificacion4_2' => 'string|nullable',
            'tb_verificacion4_3' => 'string|nullable',
            'tb_verificacion4_4' => 'string|nullable',
            'tb_verificacion4_5' => 'string|nullable',
            'tb_verificacion4_6' => 'string|nullable',
            'tb_verificacion4_7' => 'string|nullable',
            'tb_verificacion4_8' => 'string|nullable',
            'tb_verificacion4_9' => 'string|nullable',
            'tb_verificacion5_1' => 'string|nullable',
            'tb_verificacion5_2' => 'string|nullable',
            'tb_verificacion5_3' => 'string|nullable',
            'tb_verificacion5_4' => 'string|nullable',
            'tb_verificacion5_5' => 'string|nullable',
            'tb_verificacion5_6' => 'string|nullable',
            'tb_verificacion5_7' => 'string|nullable',
            'tb_verificacion5_8' => 'string|nullable',
            'tb_verificacion5_9' => 'string|nullable',
            'indicador1' => 'float|nullable',
            'indicador2' => 'float|nullable',
            'indicador3' => 'float|nullable',
            'indicador4' => 'float|nullable',
            'proteico1' => 'string|nullable',
            'proteico2' => 'string|nullable',
            'proteico3' => 'string|nullable',
            'proteico4' => 'string|nullable',
            'proteico5' => 'string|nullable',
            'proteico6' => 'string|nullable',
            'proteico7' => 'string|nullable',
            'proteico8' => 'string|nullable',
            'leguminosa1' => 'string|nullable',
            'leguminosa2' => 'string|nullable',
            'leguminosa3' => 'string|nullable',
            'leguminosa4' => 'string|nullable',
            'leguminosa5' => 'string|nullable',
            'leguminosa6' => 'string|nullable',
            'leguminosa7' => 'string|nullable',
            'leguminosa8' => 'string|nullable',
            'cereal1' => 'string|nullable',
            'cereal2' => 'string|nullable',
            'cereal3' => 'string|nullable',
            'cereal4' => 'string|nullable',
            'cereal5' => 'string|nullable',
            'cereal6' => 'string|nullable',
            'cereal7' => 'string|nullable',
            'cereal8' => 'string|nullable',
            'tuberculos1' => 'string|nullable',
            'tuberculos2' => 'string|nullable',
            'tuberculos3' => 'string|nullable',
            'tuberculos4' => 'string|nullable',
            'tuberculos5' => 'string|nullable',
            'tuberculos6' => 'string|nullable',
            'tuberculos7' => 'string|nullable',
            'tuberculos8' => 'string|nullable',
            'verdura1' => 'string|nullable',
            'verdura2' => 'string|nullable',
            'verdura3' => 'string|nullable',
            'verdura4' => 'string|nullable',
            'verdura5' => 'string|nullable',
            'verdura6' => 'string|nullable',
            'verdura7' => 'string|nullable',
            'verdura8' => 'string|nullable',
            'jugo1' => 'string|nullable',
            'jugo2' => 'string|nullable',
            'jugo3' => 'string|nullable',
            'jugo4' => 'string|nullable',
            'jugo5' => 'string|nullable',
            'jugo6' => 'string|nullable',
            'jugo7' => 'string|nullable',
            'jugo8' => 'string|nullable',
            'cdp' => 'string|nullable',
            'placa_vehiculo' => 'string|nullable',
            'numero_sedes' => 'integer|nullable',
            'nombre1' => 'string|nullable',
            'nombre2' => 'string|nullable',
            'nombre3' => 'string|nullable',
            'nombre4' => 'string|nullable',
            'hora_salida1' => 'string|nullable',
            'hora_salida2' => 'string|nullable',
            'hora_salida3' => 'string|nullable',
            'hora_salida4' => 'string|nullable',
            'temperatura_salida1' => 'string|nullable',
            'temperatura_salida2' => 'string|nullable',
            'temperatura_salida3' => 'string|nullable',
            'temperatura_salida4' => 'string|nullable',
            'hora_llegada1' => 'string|nullable',
            'hora_llegada2' => 'string|nullable',
            'hora_llegada3' => 'string|nullable',
            'hora_llegada4' => 'string|nullable',
            'temperatura_llegada1' => 'string|nullable',
            'temperatura_llegada2' => 'string|nullable',
            'temperatura_llegada3' => 'string|nullable',
            'temperatura_llegada4' => 'string|nullable',
            'cantidad_raciones1' => 'integer|nullable',
            'cantidad_raciones2' => 'integer|nullable',
            'cantidad_raciones3' => 'integer|nullable',
            'cantidad_raciones4' => 'integer|nullable',
            'nombre_apoyo' => 'string|nullable',
            'cedula_apoyo' => 'string|nullable',
            'cargo_apoyo' => 'string|nullable',
            'telefono_apoyo' => 'string|nullable',
            'nombre_atiende' => 'string|nullable',
            'cedula_atiende' => 'string|nullable',
            'cargo_atiende' => 'string|nullable',
            'telefono_atiende' => 'string|nullable',
            'observaciones_recibe' => 'string|nullable',
        ]);

        $data['created_by'] = Auth::id();

        $registro = CtVerificacionCct::create($data);

        // Manejar los archivos (si aplica)
        if ($request->hasFile('files')) {
            foreach ($request->file('files') as $file) {
                // Guardar el archivo en el directorio correspondiente
                $filePath = $file->store('tecnico/ct_verificacion_cct/' . $registro->id, 'public');

                // Crear el registro en la tabla attachments
                Attachment::create([
                    'form_name' => 'ct_verificacion_cct',
                    'form_id' => $registro->id,
                    'file_path' => $filePath,
                    'original_name' => $file->getClientOriginalName(),
                    'file_type' => $file->getClientMimeType(),
                ]);
            }
        }

        return response()->json([
            'message' => 'Registro creado exitosamente.',
            'data' => $registro,
        ], 201);
    }

    public function show($id)
    {
        return response()->json(CtVerificacionCct::findOrFail($id));
    }

    public function update(Request $request, $id)
    {
        $registro = CtVerificacionCct::findOrFail($id);
        $registro->update($request->all());

        return response()->json($registro);
    }
}
